# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
target 'ReadNode' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReadNode
pod "Kingfisher"
pod "Hero"
pod "Popover"
pod "SVProgressHUD"
pod "Alamofire"
pod "YYModel"
pod "SwipeCellKit"

end
